import type { HistoricalDnaRow, WaveProfile } from './types';

type SeedInput = {
  slug: string;
  canonical_name: string;
  wave_profile: WaveProfile;
  origin_region: string;
  origin_signal_start: string | null;
  origin_peak_date: string;
  target_signal_start: string | null;
  target_peak_date: string | null;
  plateau_days: number | null;
  decline_start_date: string | null;
  peak_search_volume: number | null;
  success_rate: number | null;
  notes: string | null;
  reference_urls?: string[];
  dna_features?: Record<string, unknown>;
};

function daysBetween(from: string, to: string): number {
  const a = new Date(from);
  const b = new Date(to);
  return Math.round((b.getTime() - a.getTime()) / (1000 * 60 * 60 * 24));
}

function toRow(seed: SeedInput): HistoricalDnaRow {
  const target_market = 'ES';
  const delay_days_to_target =
    seed.target_peak_date && seed.origin_peak_date
      ? daysBetween(seed.origin_peak_date, seed.target_peak_date)
      : null;
  const decline_days =
    seed.decline_start_date && seed.target_peak_date
      ? daysBetween(seed.target_peak_date, seed.decline_start_date)
      : null;

  return {
    id: `demo-${seed.slug}`,
    canonical_name: seed.canonical_name,
    slug: seed.slug,
    product_line: 'kids_collectibles_vending',
    wave_profile: seed.wave_profile,
    origin_region: seed.origin_region,
    origin_signal_start: seed.origin_signal_start,
    origin_peak_date: seed.origin_peak_date,
    target_market,
    target_signal_start: seed.target_signal_start,
    target_peak_date: seed.target_peak_date,
    delay_days_to_target,
    plateau_days: seed.plateau_days,
    decline_start_date: seed.decline_start_date,
    decline_days,
    peak_search_volume: seed.peak_search_volume,
    success_rate: seed.success_rate,
    reference_urls: seed.reference_urls ?? [],
    notes: seed.notes,
    dna_features: seed.dna_features ?? {},
  };
}

/** 25 casos ADN — espejo del seed SQL (demo offline sin Supabase). */
const SEED_INPUTS: SeedInput[] = [
  {
    slug: 'labubu',
    canonical_name: 'Labubu Blind Box',
    wave_profile: 'micro_viral_playground',
    origin_region: 'asia',
    origin_signal_start: '2024-04-01',
    origin_peak_date: '2024-08-01',
    target_signal_start: '2024-11-20',
    target_peak_date: '2024-11-30',
    plateau_days: 45,
    decline_start_date: '2025-03-01',
    peak_search_volume: 85000,
    success_rate: 0.91,
    notes:
      'Validado 2026-06: pico global ~ago-2024 (Lisa/TikTok). Pico ES: pop-up Barcelona 30-nov-2024. Delay ~121d.',
    dna_features: { virality: 'tiktok', audience: 'teens_adults', validated: '2026-06' },
  },
  {
    slug: 'dumplings-squishy',
    canonical_name: 'Dumpling Squishy Steamer',
    wave_profile: 'micro_viral_playground',
    origin_region: 'usa',
    origin_signal_start: '2025-08-01',
    origin_peak_date: '2025-11-15',
    target_signal_start: null,
    target_peak_date: null,
    plateau_days: null,
    decline_start_date: null,
    peak_search_volume: 120000,
    success_rate: 0.88,
    notes:
      'Validado 2026-06 (origen US): RMS Mystery Dumpling, 500M+ views TikTok 2025. Sell-outs Five Below. Patio ES sin señal — reloj largo.',
    reference_urls: [
      'https://toybook.com/rms-usa-five-below-dumpling-giveaway-news/',
      'https://www.businesswire.com/news/home/20260319125442/en/A-Viral-Sensation-Turned-Retail-Juggernaut-RMS-USAs-Mystery-Dumpling-Continues-Its-Sell-Out-Streak',
      'https://www.rms-usa.com/press/golden-ticket-mystery-dumpling',
    ],
    dna_features: {
      virality: 'tiktok_kids',
      validated: '2026-06',
      status: 'active_us_only',
      es_pending: true,
    },
  },
  {
    slug: 'pop-it',
    canonical_name: 'Pop It Fidget',
    wave_profile: 'micro_viral_playground',
    origin_region: 'usa',
    origin_signal_start: '2020-11-15',
    origin_peak_date: '2021-04-01',
    target_signal_start: '2021-02-01',
    target_peak_date: '2021-05-15',
    plateau_days: 45,
    decline_start_date: '2021-09-01',
    peak_search_volume: 200000,
    success_rate: 0.75,
    notes:
      'Validado 2026-06: viral TikTok US primavera 2021 (mono Gaitlyn Rae). ES: +500% ventas mayo 2021, patios/colegios. Delay ~44d.',
    reference_urls: [
      'https://www.bbc.com/news/business-58408570',
      'https://www.huffingtonpost.es/entry/pop-it-que-son-como-jugar_es_609cf92de4b069dc48f76689.html',
      'https://www.theguardian.com/lifeandstyle/2021/may/28/pop-hit-how-rainbow-reusable-bubblewrap-became-a-playground-must-have',
    ],
    dna_features: { virality: 'tiktok', audience: 'kids', validated: '2026-06' },
  },
  {
    slug: 'pokemon-tcg-sv',
    canonical_name: 'Pokémon TCG Scarlet Violet',
    wave_profile: 'collectible_cards',
    origin_region: 'japan',
    origin_signal_start: '2023-01-20',
    origin_peak_date: '2023-03-01',
    target_signal_start: '2023-03-31',
    target_peak_date: '2023-05-15',
    plateau_days: 55,
    decline_start_date: '2024-02-01',
    peak_search_volume: 95000,
    success_rate: 0.85,
    notes:
      'Validado 2026-06: JP 20-ene, ES 31-mar-2023. Pico vending ~may-2023. Delay pico ~75d.',
    dna_features: { channel: 'vending', validated: '2026-06' },
  },
  {
    slug: 'one-piece-op01',
    canonical_name: 'One Piece Card Game OP-01',
    wave_profile: 'media_spike',
    origin_region: 'japan',
    origin_signal_start: '2022-06-01',
    origin_peak_date: '2022-08-01',
    target_signal_start: '2022-10-01',
    target_peak_date: '2023-06-01',
    plateau_days: 90,
    decline_start_date: '2024-01-01',
    peak_search_volume: 110000,
    success_rate: 0.9,
    notes: 'Media spike tras anime/Netflix. Demanda x5.',
    dna_features: { media_trigger: true },
  },
  {
    slug: 'fifa-stickers-2022',
    canonical_name: 'FIFA World Cup Stickers 2022',
    wave_profile: 'seasonal_mass',
    origin_region: 'global',
    origin_signal_start: '2022-08-15',
    origin_peak_date: '2022-11-20',
    target_signal_start: '2022-09-01',
    target_peak_date: '2022-11-27',
    plateau_days: 30,
    decline_start_date: '2023-01-15',
    peak_search_volume: 250000,
    success_rate: 0.92,
    notes: 'Validado 2026-06: pico semana 1 Mundial. ES casi simultáneo (~7d). Agotamientos Panini.',
    dna_features: { event: 'world_cup', validated: '2026-06' },
  },
  {
    slug: 'fifa-cards-2026',
    canonical_name: 'FIFA World Cup 2026 Cards',
    wave_profile: 'seasonal_mass',
    origin_region: 'uk',
    origin_signal_start: '2025-11-01',
    origin_peak_date: '2026-02-01',
    target_signal_start: '2026-01-15',
    target_peak_date: '2026-03-01',
    plateau_days: 45,
    decline_start_date: null,
    peak_search_volume: 180000,
    success_rate: 0.87,
    notes: 'Preventa activa. Retail físico agotado en formatos premium.',
    dna_features: { event: 'world_cup_2026' },
  },
  {
    slug: 'he-man-origins',
    canonical_name: 'He-Man Origins',
    wave_profile: 'kidult_nostalgia',
    origin_region: 'usa',
    origin_signal_start: '2020-09-01',
    origin_peak_date: '2021-01-15',
    target_signal_start: '2021-03-01',
    target_peak_date: '2021-06-01',
    plateau_days: 120,
    decline_start_date: '2022-06-01',
    peak_search_volume: 45000,
    success_rate: 0.78,
    notes: 'Kidult. Waves exclusivas US no traídas a tiempo en ES.',
    dna_features: { audience: 'kidult' },
  },
  {
    slug: 'superzings',
    canonical_name: 'SuperZings',
    wave_profile: 'micro_viral_playground',
    origin_region: 'europe',
    origin_signal_start: '2019-09-01',
    origin_peak_date: '2019-11-01',
    target_signal_start: '2020-01-01',
    target_peak_date: '2020-03-15',
    plateau_days: 50,
    decline_start_date: '2020-09-01',
    peak_search_volume: 70000,
    success_rate: 0.72,
    notes: 'Coleccionables deporte kids.',
  },
  {
    slug: 'squishmallows',
    canonical_name: 'Squishmallows Wave',
    wave_profile: 'micro_viral_playground',
    origin_region: 'usa',
    origin_signal_start: '2020-03-01',
    origin_peak_date: '2021-12-01',
    target_signal_start: '2021-09-01',
    target_peak_date: '2023-04-15',
    plateau_days: 90,
    decline_start_date: '2024-06-01',
    peak_search_volume: 130000,
    success_rate: 0.8,
    notes:
      'Validado 2026-06: US pico Navidad 2021. Iberia peluche #1 abr-2023 (NPD/GfK). Delay ~500d — reloj largo.',
    reference_urls: [
      'https://www.theguardian.com/business/2022/dec/09/squishmallows-go-from-tiktok-sensation-to-top-christmas-toy',
      'https://www.interempresas.net/Juguetes/482719-Squishmallows-revoluciona-el-mundo-del-peluche-desde-las-redes-sociales.html',
    ],
    dna_features: { virality: 'tiktok', audience: 'kids_teen', validated: '2026-06', long_clock: true },
  },
  {
    slug: 'sonny-angel',
    canonical_name: 'Sonny Angel',
    wave_profile: 'micro_viral_playground',
    origin_region: 'japan',
    origin_signal_start: '2023-01-01',
    origin_peak_date: '2023-04-01',
    target_signal_start: '2023-06-01',
    target_peak_date: '2023-09-01',
    plateau_days: 35,
    decline_start_date: '2024-03-01',
    peak_search_volume: 65000,
    success_rate: 0.83,
    notes: 'Mini figuras. Similar pipeline a Labubu.',
  },
  {
    slug: 'match-attax',
    canonical_name: 'Match Attax UEFA',
    wave_profile: 'collectible_cards',
    origin_region: 'uk',
    origin_signal_start: '2024-08-01',
    origin_peak_date: '2024-10-01',
    target_signal_start: '2024-09-15',
    target_peak_date: '2024-11-01',
    plateau_days: 25,
    decline_start_date: '2025-02-01',
    peak_search_volume: 55000,
    success_rate: 0.79,
    notes: 'Cartas fútbol. Delay UK→ES corto.',
    dna_features: { sport: 'football' },
  },
  {
    slug: 'lol-surprise',
    canonical_name: 'L.O.L. Surprise!',
    wave_profile: 'micro_viral_playground',
    origin_region: 'usa',
    origin_signal_start: '2017-08-01',
    origin_peak_date: '2017-11-15',
    target_signal_start: '2018-01-01',
    target_peak_date: '2018-03-01',
    plateau_days: 40,
    decline_start_date: '2018-09-01',
    peak_search_volume: 180000,
    success_rate: 0.86,
    notes: 'Blind bag coleccionables. Ola global antes del boom TikTok.',
    dna_features: { audience: 'kids_6_12' },
  },
  {
    slug: 'fidget-spinner',
    canonical_name: 'Fidget Spinner',
    wave_profile: 'micro_viral_playground',
    origin_region: 'usa',
    origin_signal_start: '2017-02-01',
    origin_peak_date: '2017-04-15',
    target_signal_start: '2017-05-01',
    target_peak_date: '2017-06-20',
    plateau_days: 30,
    decline_start_date: '2017-10-01',
    peak_search_volume: 220000,
    success_rate: 0.7,
    notes: 'Ciclo ultrarrápido. Referencia de saturación en vending.',
    dna_features: { cycle_days: 45 },
  },
  {
    slug: 'hatchimals',
    canonical_name: 'Hatchimals Colleggtibles',
    wave_profile: 'seasonal_mass',
    origin_region: 'canada',
    origin_signal_start: '2016-10-01',
    origin_peak_date: '2016-12-01',
    target_signal_start: '2017-01-15',
    target_peak_date: '2017-03-01',
    plateau_days: 35,
    decline_start_date: '2017-08-01',
    peak_search_volume: 150000,
    success_rate: 0.74,
    notes: 'Navidad-driven. Stock físico crítico en retail.',
    dna_features: { event: 'christmas' },
  },
  {
    slug: 'beyblade-burst',
    canonical_name: 'Beyblade Burst Turbo',
    wave_profile: 'micro_viral_playground',
    origin_region: 'japan',
    origin_signal_start: '2017-03-01',
    origin_peak_date: '2017-06-01',
    target_signal_start: '2017-08-01',
    target_peak_date: '2017-10-15',
    plateau_days: 50,
    decline_start_date: '2018-04-01',
    peak_search_volume: 75000,
    success_rate: 0.77,
    notes: 'Anime + patio. Relanzamiento periódico por waves.',
    dna_features: { anime_tie_in: true },
  },
  {
    slug: 'digimon-tcg-2020',
    canonical_name: 'Digimon TCG 2020',
    wave_profile: 'collectible_cards',
    origin_region: 'japan',
    origin_signal_start: '2020-02-01',
    origin_peak_date: '2020-06-01',
    target_signal_start: '2020-09-01',
    target_peak_date: '2021-02-01',
    plateau_days: 70,
    decline_start_date: '2022-01-01',
    peak_search_volume: 48000,
    success_rate: 0.76,
    notes: 'Segunda ola TCG. Canal hobby antes que vending.',
    dna_features: { tcg_wave: 2 },
  },
  {
    slug: 'bluey-toys',
    canonical_name: 'Bluey Toys & Plush',
    wave_profile: 'media_spike',
    origin_region: 'australia',
    origin_signal_start: '2021-06-01',
    origin_peak_date: '2021-10-01',
    target_signal_start: '2022-01-01',
    target_peak_date: '2022-05-01',
    plateau_days: 55,
    decline_start_date: '2023-03-01',
    peak_search_volume: 90000,
    success_rate: 0.84,
    notes: 'Streaming Disney+. Demanda sostenida en familias 3-7.',
    dna_features: { media: 'disney_plus' },
  },
  {
    slug: 'among-us-plush',
    canonical_name: 'Among Us Plush',
    wave_profile: 'media_spike',
    origin_region: 'usa',
    origin_signal_start: '2020-08-01',
    origin_peak_date: '2020-10-15',
    target_signal_start: '2020-11-01',
    target_peak_date: '2021-01-10',
    plateau_days: 25,
    decline_start_date: '2021-05-01',
    peak_search_volume: 140000,
    success_rate: 0.71,
    notes: 'Gaming viral COVID-era. Ciclo corto.',
    dna_features: { gaming_viral: true },
  },
  {
    slug: 'squid-game-merch',
    canonical_name: 'Squid Game Merch',
    wave_profile: 'media_spike',
    origin_region: 'korea',
    origin_signal_start: '2021-09-01',
    origin_peak_date: '2021-10-15',
    target_signal_start: '2021-10-20',
    target_peak_date: '2021-11-15',
    plateau_days: 14,
    decline_start_date: '2022-02-01',
    peak_search_volume: 175000,
    success_rate: 0.68,
    notes: 'Netflix global. Delay mínimo; saturación rápida.',
    dna_features: { media: 'netflix' },
  },
  {
    slug: 'demon-slayer-figures',
    canonical_name: 'Demon Slayer Figures',
    wave_profile: 'media_spike',
    origin_region: 'japan',
    origin_signal_start: '2020-10-01',
    origin_peak_date: '2021-02-01',
    target_signal_start: '2021-04-01',
    target_peak_date: '2021-08-01',
    plateau_days: 65,
    decline_start_date: '2022-06-01',
    peak_search_volume: 105000,
    success_rate: 0.88,
    notes: 'Anime theatrical. Figuras blind box en vending JP→ES.',
    dna_features: { anime: 'kimetsu' },
  },
  {
    slug: 'smiski',
    canonical_name: 'Smiski',
    wave_profile: 'micro_viral_playground',
    origin_region: 'japan',
    origin_signal_start: '2022-06-01',
    origin_peak_date: '2022-09-01',
    target_signal_start: '2023-01-01',
    target_peak_date: '2023-05-01',
    plateau_days: 40,
    decline_start_date: '2024-01-01',
    peak_search_volume: 52000,
    success_rate: 0.81,
    notes: 'Glow-in-dark mini figuras. Pipeline similar a Sonny Angel.',
    dna_features: { glow: true },
  },
  {
    slug: 'minecraft-minis',
    canonical_name: 'Minecraft Minis',
    wave_profile: 'kidult_nostalgia',
    origin_region: 'global',
    origin_signal_start: '2019-03-01',
    origin_peak_date: '2019-06-01',
    target_signal_start: '2019-08-01',
    target_peak_date: '2019-11-01',
    plateau_days: 80,
    decline_start_date: '2021-06-01',
    peak_search_volume: 62000,
    success_rate: 0.79,
    notes: 'Gaming evergreen. Waves constantes en máquinas mix.',
    dna_features: { gaming: 'minecraft' },
  },
  {
    slug: 'gabbys-dollhouse',
    canonical_name: "Gabby's Dollhouse",
    wave_profile: 'media_spike',
    origin_region: 'usa',
    origin_signal_start: '2021-01-01',
    origin_peak_date: '2021-04-01',
    target_signal_start: '2021-06-01',
    target_peak_date: '2021-09-01',
    plateau_days: 45,
    decline_start_date: '2022-04-01',
    peak_search_volume: 58000,
    success_rate: 0.75,
    notes: 'Netflix kids. Figuras sorpresa en retail tardío.',
    dna_features: { audience: 'preschool' },
  },
  {
    slug: 'calico-critters',
    canonical_name: 'Calico Critters Resurgence',
    wave_profile: 'kidult_nostalgia',
    origin_region: 'japan',
    origin_signal_start: '2020-04-01',
    origin_peak_date: '2020-08-01',
    target_signal_start: '2020-10-01',
    target_peak_date: '2021-02-01',
    plateau_days: 90,
    decline_start_date: '2022-08-01',
    peak_search_volume: 42000,
    success_rate: 0.73,
    notes: 'Nostalgia + ASMR unboxing TikTok.',
    dna_features: { asmr: true },
  },
];

export const DEMO_SEED: HistoricalDnaRow[] = SEED_INPUTS.map(toRow);

export const DEMO_SEED_COUNT = DEMO_SEED.length;
