import type { HistoricalDnaRow } from './types';

/** Datos demo locales (mismo ADN que la migración SQL) hasta conectar Supabase. */
export const DEMO_SEED: HistoricalDnaRow[] = [
  {
    id: 'demo-labubu',
    canonical_name: 'Labubu Blind Box',
    slug: 'labubu',
    product_line: 'kids_collectibles_vending',
    wave_profile: 'micro_viral_playground',
    origin_region: 'asia',
    origin_signal_start: '2024-07-01',
    origin_peak_date: '2024-09-10',
    target_market: 'ES',
    target_signal_start: '2024-10-01',
    target_peak_date: '2024-10-25',
    delay_days_to_target: 45,
    plateau_days: 21,
    decline_start_date: '2024-12-15',
    decline_days: 51,
    peak_search_volume: 85000,
    success_rate: 0.91,
    reference_urls: [],
    notes: 'Blind box diseño. Pico Asia previo a mochilas en ES.',
    dna_features: { virality: 'tiktok', audience: 'teens_adults' },
  },
  {
    id: 'demo-dumplings',
    canonical_name: 'Dumpling Squishy Steamer',
    slug: 'dumplings-squishy',
    product_line: 'kids_collectibles_vending',
    wave_profile: 'micro_viral_playground',
    origin_region: 'usa',
    origin_signal_start: '2026-03-15',
    origin_peak_date: '2026-04-10',
    target_market: 'ES',
    target_signal_start: '2026-04-20',
    target_peak_date: '2026-05-02',
    delay_days_to_target: 22,
    plateau_days: 14,
    decline_start_date: '2026-06-01',
    decline_days: 30,
    peak_search_volume: 120000,
    success_rate: 0.88,
    reference_urls: [],
    notes: 'ASMR sensorial. Delay corto por TikTok Shop.',
    dna_features: { virality: 'tiktok_kids', cycle_days: 25 },
  },
  {
    id: 'demo-pop-it',
    canonical_name: 'Pop It Fidget',
    slug: 'pop-it',
    product_line: 'kids_collectibles_vending',
    wave_profile: 'micro_viral_playground',
    origin_region: 'usa',
    origin_signal_start: '2021-02-01',
    origin_peak_date: '2021-03-15',
    target_market: 'ES',
    target_signal_start: '2021-04-01',
    target_peak_date: '2021-05-10',
    delay_days_to_target: 56,
    plateau_days: 45,
    decline_start_date: '2021-09-01',
    decline_days: 114,
    peak_search_volume: 200000,
    success_rate: 0.75,
    reference_urls: [],
    notes: 'Ola clásica patio post-TikTok inicial.',
    dna_features: {},
  },
  {
    id: 'demo-pokemon',
    canonical_name: 'Pokémon TCG Scarlet Violet',
    slug: 'pokemon-tcg-sv',
    product_line: 'kids_collectibles_vending',
    wave_profile: 'collectible_cards',
    origin_region: 'japan',
    origin_signal_start: '2023-03-01',
    origin_peak_date: '2023-04-15',
    target_market: 'ES',
    target_signal_start: '2023-05-01',
    target_peak_date: '2023-07-20',
    delay_days_to_target: 96,
    plateau_days: 60,
    decline_start_date: '2024-02-01',
    decline_days: 196,
    peak_search_volume: 95000,
    success_rate: 0.85,
    reference_urls: [],
    notes: 'Cartas licenciadas. Canal vending en crecimiento.',
    dna_features: { channel: 'vending' },
  },
  {
    id: 'demo-onepiece',
    canonical_name: 'One Piece Card Game OP-01',
    slug: 'one-piece-op01',
    product_line: 'kids_collectibles_vending',
    wave_profile: 'media_spike',
    origin_region: 'japan',
    origin_signal_start: '2022-06-01',
    origin_peak_date: '2022-08-01',
    target_market: 'ES',
    target_signal_start: '2022-10-01',
    target_peak_date: '2023-06-01',
    delay_days_to_target: 304,
    plateau_days: 90,
    decline_start_date: '2024-01-01',
    decline_days: 214,
    peak_search_volume: 110000,
    success_rate: 0.9,
    reference_urls: [],
    notes: 'Media spike tras anime/Netflix. Demanda x5.',
    dna_features: { media_trigger: true },
  },
  {
    id: 'demo-fifa22',
    canonical_name: 'FIFA World Cup Stickers 2022',
    slug: 'fifa-stickers-2022',
    product_line: 'kids_collectibles_vending',
    wave_profile: 'seasonal_mass',
    origin_region: 'global',
    origin_signal_start: '2022-08-01',
    origin_peak_date: '2022-11-01',
    target_market: 'ES',
    target_signal_start: '2022-09-01',
    target_peak_date: '2022-11-20',
    delay_days_to_target: 19,
    plateau_days: 30,
    decline_start_date: '2023-01-15',
    decline_days: 56,
    peak_search_volume: 250000,
    success_rate: 0.92,
    reference_urls: [],
    notes: 'Estacional. Colapso quioscos físicos.',
    dna_features: { event: 'world_cup' },
  },
];
