import type { LiveSignalRow } from './radar-types';

/** 5 señales radar demo — alineadas con pilotos ADN/LATAM. */
export const DEMO_RADAR: LiveSignalRow[] = [
  {
    id: 'radar-labubu',
    canonical_name: 'Labubu / Pop Mart',
    slug: 'radar-labubu',
    status: 'watching',
    origin_region: 'asia',
    detected_at: '2026-06-01T00:00:00Z',
    origin_peak_date: '2024-08-01',
    predicted_es_peak_date: '2025-02-15',
    predicted_delay_days: 121,
    dna_match_slug: 'labubu',
    dna_match_score: 0.91,
    confidence: 'high',
    signal_source: 'ADN validado + scrape 48h',
    notes:
      'Piloto 1/5. Post-pico ES; vigilar nueva ola blind box. Ref. LATAM ~46d antes de ES.',
    reference_urls: [],
  },
  {
    id: 'radar-pop-it',
    canonical_name: 'Pop It Fidget',
    slug: 'radar-pop-it',
    status: 'watching',
    origin_region: 'usa',
    detected_at: '2026-06-01T00:00:00Z',
    origin_peak_date: '2021-03-15',
    predicted_es_peak_date: null,
    predicted_delay_days: 30,
    dna_match_slug: 'pop-it',
    dna_match_score: 0.75,
    confidence: 'medium',
    signal_source: 'ADN histórico + scrape 48h',
    notes:
      'Piloto 2/5. Ciclo 2021 archivado; scrape detecta resurgencias. LATAM suele ir antes de ES.',
    reference_urls: [],
  },
  {
    id: 'radar-pokemon-sv',
    canonical_name: 'Pokémon TCG Escarlata y Púrpura',
    slug: 'radar-pokemon-sv',
    status: 'emerging',
    origin_region: 'asia',
    detected_at: '2026-06-01T00:00:00Z',
    origin_peak_date: '2023-03-01',
    predicted_es_peak_date: '2023-05-15',
    predicted_delay_days: 75,
    dna_match_slug: 'pokemon-tcg-sv',
    dna_match_score: 0.85,
    confidence: 'high',
    signal_source: 'ADN validado + scrape 48h',
    notes:
      'Piloto 3/5. Demanda vending/cartas. LATAM retail suele ir después de EU.',
    reference_urls: [],
  },
  {
    id: 'radar-fifa-2026',
    canonical_name: 'Cromos Mundial 2026 — Panini',
    slug: 'radar-fifa-2026',
    status: 'emerging',
    origin_region: 'global',
    detected_at: '2026-01-10T00:00:00Z',
    origin_peak_date: '2026-02-01',
    predicted_es_peak_date: '2026-06-18',
    predicted_delay_days: 7,
    dna_match_slug: 'fifa-stickers-2022',
    dna_match_score: 0.89,
    confidence: 'high',
    signal_source: 'Evento programado + scrape 48h',
    notes:
      'Piloto 4/5. Torneo 11-jun-2026. Patrón FIFA 2022 (paralelo LATAM/ES).',
    reference_urls: [],
  },
  {
    id: 'radar-squishmallows',
    canonical_name: 'Squishmallows',
    slug: 'radar-squishmallows',
    status: 'watching',
    origin_region: 'usa',
    detected_at: '2026-06-01T00:00:00Z',
    origin_peak_date: '2021-07-01',
    predicted_es_peak_date: null,
    predicted_delay_days: 45,
    dna_match_slug: 'squishmallows',
    dna_match_score: 0.72,
    confidence: 'medium',
    signal_source: 'ADN histórico + scrape 48h',
    notes:
      'Piloto 5/5. Oleada US; LATAM import ~2 sem después de EU en histórico.',
    reference_urls: [],
  },
];
